---
- name: Kubernetes | Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true

- name: Kubernetes | Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Kubernetes | Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
